baseurl = "https://manishmarahatta.com.np"
title = "Emacs Jedi"
languageCode = "en-us"
disqusShortname = "manishmarahatta"
copyright = "Copyright (c) 2012 - 2019, Manish Marahatta; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Manish Marahatta"

[indexes]
    tag = "tags"
    topic = "topics"
